### ISSUE TITLE
What's your torch version please?

### ISSUE THREAD

**Issue by xianfenggao** [Zhang-Jack/adversarial_yolo2#1]
We run the demo.py as " demo.py cfg/yolov2.cfg weights/yolo.weights".
And we got the error :
Traceback (most recent call last):
  File "D:/adversarial_yolo2-master/demo.py", line 46, in <module>
    demo(cfgfile, weightfile)
  File "D:/adversarial_yolo2-master/demo.py", line 34, in demo
    draw_img = plot_boxes_cv2(img, bboxes, None, class_names)
  File "D:\adversarial_yolo2-master\utils.py", line 217, in plot_boxes_cv2
    x1 = int(round((box[0] - box[2]/2.0) * width))
TypeError: type Tensor doesn't define __round__ method

After some debugging, we thought the reason may result from the different version of Torch.
Our torch version is  1.0.1

**Comment by xianfenggao** [comment]
It has been solved by changing "round" to "torch.round". 
Sorry for disturbing.
